export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const REGISTER = "REGISTER";
export const REQUEST_SSO = "REQUEST_SSO";
export const CHECK_LOGIN = "CHECK_LOGIN";
export const SEND_SSO_CODE = "SEND_SSO_CODE";
export const EDIT_AUTH_VALUE = "SET_AUTH_VALUE";

export const SET_USER = "SET_USER";
export const SET_LOADING = "SET_LOADING";
export const SET_USER_CLASS = "SET_USER_CLASS";
export const SET_USER_CLASSES = "SET_USER_CLASSES";
export const SET_USER_REQUESTS = "SET_USER_REQUESTS";
export const REQUEST_JOIN_CLASS = "REQUEST_JOIN_CLASS";
export const ACCEPT_JOIN_REQUEST = "ACCEPT_JOIN_REQUEST";



export const SET_CLASS = "SET_CLASS";
export const SET_CLASSES = "SET_CLASSES";
export const CREATE_CLASS = "CREATE_CLASS";
export const REQUEST_CLASS = "REQUEST_CLASS";
export const EDIT_CLASS_VALUE = "EDIT_CLASS_VALUE";
export const SET_CLASS_TEACHER = "SET_CLASS_TEACHER";
export const SET_EDITING_CLASS = "SET_EDITING_CLASS";
export const SET_POPULAR_CLASSES = "SET_POPULAR_CLASSES";
export const ACCEPT_CLASS_REQUEST = "ACCEPT_CLASS_REQUEST";
export const REJECT_CLASS_REQUEST = "REJECT_CLASS_REQUEST";
export const SET_CREATE_CLASS_ERROR = "SET_CREATE_CLASS_ERROR";

export const SET_ADMINS = "SET_ADMINS";
export const SET_ACCOUNTS = "SET_ACCOUNTS";
export const SET_TEACHERS = "SET_TEACHERS";
export const SET_STUDENTS = "SET_STUDENTS";
export const CREATE_ACCOUNT = "CREATE_ACCOUNT";
export const EDIT_NEW_ACCOUNT = "EDIT_NEW_ACCOUNT";
export const SET_CREATE_ACCOUNT_ERROR = "SET_CREATE_ACCOUNT_ERROR";

