export const SOCKET_EVENT_LOGIN = "LOGIN_SOCKET_EVENT";
export const SOCKET_EVENT_LOGOUT = "LOGOUT_SOCKET_EVENT";
export const SOCKET_EVENT_APP_CONFIG = "APP_CONFIG_SOCKET_EVENT";
export const SOCKET_EVENT_NOTIFICATION = "NOTIFICATION_SOCKET_EVENT";
