export const SOCKET_ROOM_SALES = "SALES_ROOM";
export const SOCKET_ROOM_ADMINS = "ADMINS_ROOM";
export const SOCKET_ROOM_TEACHERS = "TEACHERS_ROOM";
export const SOCKET_ROOM_STUDENTS = "STUDENTS_ROOM";